version: '3.3'

services:
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: api
    env_file: ./.env
    ports:
      - $NODE_PORT:$NODE_PORT
    depends_on:
      - mysqldb
  ui:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    image: ui
    ports:
      - $NGINX_PORT:$NGINX_PORT
    volumes:
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - api

volumes:
  db-config:
  db-data: